name: destiny_slack_bot
author: P.Y. Laligand
version: 0.0.1
description: A Slack bot exposing various Destiny-related utilities.
dependencies:
  bungie_client:
    git:
      url: https://github.com/pylaligand/dart-bungie-client.git
      ref: 05f1253f194c15d1c4b0356263dc4bbc22d0b23f
  http: ^0.11.3+3
  logging: ^0.11.2
  postgresql: ^0.3.3
  shelf: ^0.6.5
  shelf_route: ^0.14.1
  timezone: ^0.5.0-dev
dev_dependencies:
  archive: ^1.0.25
  args: ^0.13.4
  mockito: ^0.11.0
  path: ^1.3.9
  quiver: '^0.21.0'
  sqlite: ^0.4.2
  test: ^0.12.13
